const HARFLER = [l
        "A",
        "B",
        "C",
        "Ç",
        "D",
        "E",
        "F",
        "G",
        "H",
        "I/İ",
        "K",
        "L",
        "M",
        "N",
        "O",
        "Ö",
        "P",
        "R",
        "S",
        "Ş",
        "T",
        "U",
        "Ü",
        "V",
        "Y",
        "Z",
      ];
      const HARF_DOSYA_ESLEME = {
        A: "a",
        B: "b",
        C: "c",
        Ç: "ch",
        D: "d",
        E: "e",
        F: "f",
        G: "g",
        H: "h",
        "I/İ": "i",
        K: "k",
        L: "l",
        M: "m",
        N: "n",
        O: "o",
        Ö: "oo",
        P: "p",
        R: "r",
        S: "s",
        Ş: "sh",
        T: "t",
        U: "u",
        Ü: "uu",
        V: "v",
        Y: "y",
        Z: "z",
      };
      const EMAILJS_SERVICE_ID = "service_ojr0p6q";
      const EMAILJS_TEMPLATE_ID = "template_dlmjr0w";
      const EMAILJS_PUBLIC_KEY = "D01aRDtRbWdqpLIjm";
      const OYUN_SURESI = 360;

      // Oyun durum değişkenleri (Doğru, yanlış sayıları da buraya eklendi)
      let oyunDurumu = {
        harfDurumlari: {},
        harfCevaplari: {},
        yuklenenSorular: {},
        secilenSorular: {},
        mevcutHarfIndeks: 0,
        mevcutHarf: "A",
        kalanSure: OYUN_SURESI,
        zamanlayici: null,
        pasKuyrugu: [],
        pasModu: false,
        pasIndeks: 0,
        calisiyor: false,
        puan: 0,
        dogruSayisi: 0,
        yanlisSayisi: 0,
        pasSayisi: 0,
      };
